# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa2bc176d3758bbb6b1de92df188f64dda9c23590015c523e2ad123ac006071720e873c0e17419910e7a37e4f123cbf087c663e1f0171f87cfd270262b4900aa

test:
  secret_key_base: 52289ce99d2ada409b97c714b358181a3393ed54b5006dc64bde3d3dca7b6b33dd2182216e92af96ab5c5c3800f045e6764da7dacdfcbd42d2da8635608acf09

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
